# 异常处理学习笔记

- [.NET/C#_建议的异常处理原则](#.NET/C#_建议的异常处理原则)
    - [不恰当的异常处理](#不恰当的异常处理)
    - [总揽全局--分层异常处理](#%总揽全局--分层异常处理)
    - [定出原则--职责分明](#定出原则--职责分明)
        - [任务执行细节](#任务执行细节)
        - [顶层UI/命令或API](#顶层UI/命令或API)
        - [程序统一处理](#程序统一处理)
        - [框架](#框架)
- [应该抛出什么异常？不应该抛出什么异常](#应该抛出什么异常？不应该抛出什么异常)
    - [究竟是谁错了](#究竟是谁错了)
    - [使用错误应该第一时间抛出](#使用错误应该第一时间抛出)
    - [永远不应让实现错误抛出](#永远不应让实现错误抛出)
    - [对于环境错误，关注于规避和恢复](#对于环境错误，关注于规避和恢复)
    - [程序中的异常](#程序中的异常)
- [使用 ExceptionDispatchInfo 捕捉并重新抛出异常](#使用 ExceptionDispatchInfo 捕捉并重新抛出异常)

异常类应该针对应用场景定制，而不是用基础的异常类型代替。

异常处理目标：
1. 使程序代码混乱最小化
2. 捕获并保留诊断信息
3. 通知合适的人员
4. 采用合适的方式结束异常活动

要点：
1. 避免过度使用异常
    * 不要把异常和普通错误混淆在一起
    * 不要使用异常处理代替流程控制
2. 避免使用庞大的try块
3. 对异常进行分门别类处理
4. 不要忽略异常
    * 要处理异常，对异常要进行合适的修复
    * 重新抛出异常
    * 在合适的层处理异常

## .NET/C#_建议的异常处理原则

### 不恰当的异常处理
1. 严重的体验下降
2. 巨大的额外维护成本

### 总揽全局--分层异常处理
异常处理通常可以分为四层：
1. 任务执行细节
2. 调用任务执行的顶级UI，顶级命令或包办完整功能的API
3. 线程级别和应用程序域级别
4. 驱动模块或应用程序的框架

``` 
线程顶级或应用程序域顶级
Dispatcher.UnhandledException + AppDomain.UnhandledException
Task1       Task2       Task3       OtherTask
Command     Api.xxx     Click       
任务的细节   任务的细节   任务的细节   
```

### 定出原则--职责分明
#### 任务执行细节
* 组件库/公共组件
* 业务实现代码

处理原则：
* 提前判断参数和状态，不满足则抛出异常
    如果调用方法需要准备一些状态或参数才能正常执行，那么必须提前判断状态；    如果判断不通过，需要抛出异常提示调用方需要正确的调用。
* 执行方法承诺的任务，若无法履行承诺则抛出异常
    如果调用的更底层的方法抛出了异常，那么推荐**保留这些异常对外抛出**，要么抛出自己的异常并将底层异常包装层内部异常
* 如果异常会导致状态错误或应用程序雪崩，需要恢复并重新抛出异常
    `catch` 是用来恢复错误的，而不是用来防止崩溃的。
    `finally` 是用来恢复状态的。

#### 顶层UI/命令或API
* 对顶层 UI 或命令来说，提前判断的参数通常是用户的输入和当前应用程序的若干状态
    对用户输入来说，提前从交互上防止用户出错是最佳的方式，但也不可避免会存在遗漏，这时肯定不能直接抛异常给用户；所以此时的最佳处理方案是给出适当的UI反馈以告知用户出现的问题和建议的恢复方法。
    对于程序当前的状态来说，如果不符合执行某个命令的要求，这个命令应该被禁用并告知用户禁用原因。
* 对顶级 UI 或命令来说，承诺的任务已经开始包含必要的异常处理以及与此处理相关的交互。
    也就是说，`catch` 掉**已知的**几种异常并用友好的 UI 交互形式与用户进行互动也是承诺的一部分。既然承诺的任务能够达成，也不需要抛出异常。(未知原因的异常依然不应该私自处理，因为着依然会导致异常问题难以定位，何况还是未知异常。)
* 应用程序级别对外公开的 API 考虑到安全性问题，也会有限地通过 UI 交互吞掉部分已知的异常。

#### 程序统一处理
`Dispatcher.UnhandledException` 可以处理掉但概念 UI 线程上未经处理的异常
`AppDomain.UnhandledException` 可以让我们知道当前应用程序域钟所有未经处理的异常

#### 框架
框架代码可能被业务代码调用，也可能调用业务代码。无论哪种，框架从来都不能相信业务代码按照要求和契约来编程。
处理框架代码被调用时，以正常实现细节被调用的异常处理原则一样即可--确保参数正确，承诺完成并且不完成就抛出异常。
处理框架调用业务代码时，几乎一定要处理业务代码任何种类崩溃的情况。也就是说，几乎需要恢复错误然后重新抛出异常。


## 应该抛出什么异常？不应该抛出什么异常

### 究竟是谁错了
程序从上到下从里到外都是执行一个个包含某种目的的代码，我们将其称之为“任务”。当需要完成某项任务时，任务的完成情况只有两种结果：
1. 成功
2. 失败
抛出异常后，报告错误只是手段，真正要做的是**帮助开发者修复错误**。
首先区分谁错了：
* 任务的使用者错了，使用错误
    ArgumentException:参数错误
        ArgumentNullException:参数不应该传入null
        ArgumentOutOfRangeException:参数中序号超出范围
        InvalidEnumArgumentException:参数枚举值不正确
    InvalidOperationException:当前状态不允许此操作
        ObjectDisposedException:对象已经Dispose
    NotSuppertedException:不支持进行此操作
        PlatformNotSupportedException:在此平台下不支持
* 任务的执行代码写错了，实现错误
    NullReferenceException
    IndexOutOfRangeException
    InvalidCastException
    StackOverflow
    OutOfMemoryException
    AccessViolationException:使用非托管内存发生错误
    BadImageFormatException
    TypeLoadException
* 任务执行时所在的环境不符合预期，环境错误
    IOException
    Win32Exception
    ...
* 其他错误
    NotImplementedException:功能还在开发中

### 使用错误应该第一时间抛出

### 永远不应让实现错误抛出
1. 永远不应该主动用 `throw` 抛出实现错误章节中提到任何异常
2. 如果发现这些异常，应该第一时间解决
**修改源头上就已经不正确的代码，才是真正解决问题**

### 对于环境错误，关注于规避和恢复
当发生了环境错误，我们更管关注于**是什么环境下导致了异常**，以及**程序是否处理了这样的异常并恢复错误**。

.NET 中已经为我们准备了很多场景下的多套环境异常，例如 IO 相关的异常，网络连接相关的异常。这些异常都不是我们应该抛出的。

### 程序中的异常
在异常处理中，每一位开发者应该从根源上在自己的代码中消灭“实现异常”（而不是“逃避”），同时在“使用异常”的帮助下正确调用其他方法，那么代码中将只剩下“环境异常”（和小部分性能导致的“实现异常”）。

此时，开发者们将有更多的精力关注在“解决的具体业务”上面，而不是不停地解决编码上的 BUG。

特别的，“实现异常”可以被单元测试进行有效的检测。


## 使用 ExceptionDispatchInfo 捕捉并重新抛出异常

当你跑起了一个异步线程，并用 await 异步等待时，有没有好奇为什么能够在主线程 catch 到异步线程的异常？

当你希望在代码中提前收集好异常，最后一并把收集到的异常抛出的时候，能不能做到就像在原始异常发生的地方抛出一样？

本文介绍 ExceptionDispatchInfo，专门用于重新抛出异常。它在 .NET Framework 4.5 中首次引入，并原生在 .NET Core 和 .NET Standard 中得到支持。

先探索为什么需要重新抛出异常，再了解如何最佳地重新抛出异常。如果你只希望了解 ExceptionDispatchInfo，请直接从以下导航中点击跳转到最后一节。

重新抛出异常
说起重新抛出异常，你是否会认为就是写出如下代码？

``` C#
try
{
    DoButExceptionsMayOccur();
}
catch(Exception ex)
{
    // 在这里进行抢救。
    // 永远不要写出下面这句代码！（Don't write the code below forever!）
    throw ex;
}
```

为了防止这段代码被意外复制出去危及项目，我特地在注释中标明了永远不应该直接写出 throw ex 这样的句子！

这是因为 throw 语句会为异常的实例填充调用栈信息，范围为 throw 的地方开始，到 catch 的地方结束。也就是说，在异常刚刚发生的时候，也就是 DoButExceptionsMayOccur 里面的某一个调用会成为调用栈的起点，上面写了 catch 所在的函数会成为调用栈的终点。然而，一旦在 catch 中写出了 throw ex 这样的语句，那么 ex 中的调用栈将会被重写，范围从这一句 throw 开始，到外面能 catch 的地方为止。

具体说来，假设上面那段代码出现在 Test 方法中，里面的 DoButExceptionsMayOccur 调用了方法 Inner，Inner 中发生了异常；而 Outer 调用了 Test 方法，Outer 中也 catch 了异常；即整个调用链为 Outer->Test->DoButExceptionsMayOccur->Inner。那么，当刚刚 catch 到异常时，ex 的调用栈为 Test->DoButExceptionsMayOccur->Inner，而如果写了 throw ex，那么 Outer 中将只能发现调用栈为 Outer->Test，丢失了内部真正出错的原因，这对诊断和修复异常非常不利！

两次抛出异常时收获的调用栈

如果只是为了解决上述文字中所说的问题，其实只需要去掉那个 ex 即可，即：

``` C#
try
{
    DoButExceptionsMayOccur();
}
catch(Exception)
{
    // 在这里进行抢救。
    throw;
}
```

然而，有时候这个异常并不直接从这里抛出（例如后台线程），或者说我们期望这是一个分步骤收集的异常（例如遍历）。这两种情况都有一个共同特点，就是重新抛出的地方根本就不在 catch 的地方。

后台线程的例子：

``` C#
Exception exception = null;
DoSomething(() =>
{
    // 这个 try-catch 块将在另一个线程执行。
    try
    {
        DoButExceptionsMayOccur();
    }
    catch(Exception ex)
    {
        exception = ex;
    }
});
if (exception != null)
{
    // 重新抛出异常。
}
```

收集异常的例子：

``` C#
List<Exception> exceptions = new List<Exception>();
foreach(var item in collection)
{
    try
    {
        DoButExceptionsMayOccur(item);
    }
    catch(Exception ex)
    {
        exceptions.Add(ex);
    }
}
if (exceptions.Any())
{
    // 重新抛出异常。
}
```

使用内部异常
.NET Framework 早期就提供了内部异常功能，专为解决保留调用栈而重新抛出异常而生。上面两段代码标记为// 重新抛出异常。的注释部分改为：

``` C#
// 对应第一种情况。
throw new XxxException(ex);
// 对应第二种情况。
throw new AggregateException(exceptions);
```

于是两边的调用栈就被分别保留在了多个不同的 Exception 实例中。然而看异常总要一层层点开查看，始终不便。尤其是从产品中收集异常时，如何在异常分析系统中显示和分析也是个问题。

ExceptionDispatchInfo
如果将第一种情况写为：

``` C#
ExceptionDispatchInfo.Capture(ex).Throw();
```

那么，这时外面的方法再 catch 异常，则会从外层直接看到里层，只在中间插入了一段文字，却看起来就像直接从原始出处抛出一样。

第二种情况写为：
``` C#
if(exceptions.Count == 1)
{
    ExceptionDispatchInfo.Capture(exceptions.First()).Throw();
}
else if(exceptions.Count > 1)
{
    throw new AggregateException(exceptions);
}
```

使用这种方式，你看到的调用栈将是这样的：

使用 ExceptionDispatchInfo 的调用栈

至于多个异常的情况，那就只能使用内部异常来处理了。

而这些，正是 Task 管理异步线程异常时采用的策略——单个异常直接在调用线程直接抛出，多个异常抛出 AggregateException。


